GET http://localhost:3000/api/notes

###
GET http://localhost:3000/api/notes/6a45cc0563c82ddc5421c5ca

###
POST http://localhost:3000/api/notes
Content-Type: application/json

{
  "title": "Nota 2",
  "description": "Nota de Prueba 2"
}

###
DELETE http://localhost:3000/api/notes/6a45cde4c16615cebe151d76

###
PUT http://localhost:3000/api/notes/6a45cc0563c82ddc5421c5ca
Content-Type: application/json

{
  "title": "Nota Actualizada",
  "description": "Nota de Prueba Actualizada"
}